spring:
  server:
    port: 8082
  redis.host: localhost
  redis.port: 6379
  redis.timeout: 60000
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: Zmf@0522
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        


