spring:
  port: 8082
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: Zmf@0522
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

