version: "3.9"
services:
  redis:
    image: redis:7
    ports: [ "6379:6379" ]
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: [ "5432:5432" ]
  app:
    build: .
    depends_on: [ db, redis ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inventory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports: [ "8080:8080" ]
